project:
  license: ""
  copyright: ""
  author: INFOTEC DAAP
  version: 1.0.0

site_name: Lineamientos Infraestructura

theme:
  name: material
  custom_dir: overrides
  language: es
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
    - content.code.copy

  static_templates:
    - 404.html
  
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: claro
      toggle:
        icon: material/weather-night
        name: Cambiar al modo oscuro
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Cambiar al modo claro

  logo: assets/imagenes/logo_infotec.png

extra:
  homepage: https://www.infotec.mx/es/Infotec/
  social:
    - icon: octicons/mail-24
      link: mailto:arquitectura.daap@gmail.com
  harbor: https://harbor-gep.infotec.mx
  gitlab: https://gitlab-gep.infotec.mx

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      lang: es
      prebuild_index: true
  - git-revision-date-localized:
      locale: es
      type: date
      fallback_to_build_date: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
  - macros

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets:
      auto_append:
          - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

nav:
  - Inicio:
    - index.md
    - inicio/herramientas.md
    - inicio/lineamientos.md
    - inicio/colaboracion.md
  - Kubernetes:
    - kubernetes/index.md
    - Rancher:
      - kubernetes/rancher/index.md
      - Prueba de concepto:
        - kubernetes/rancher/rancher-instalacion.md
    - Despliegue:
      - kubernetes/ejemplo-sicosel/index.md
      - kubernetes/ejemplo-sicosel/instalacion.md
